### ISSUE TITLE
테스트 유닛 문드드립니다.

### ISSUE THREAD

**Issue by linkbp** [woowabros/OrderRelaySampleCode#10]
혹시 테스트 유닛에서 연속된 주문 처리가 넘어 가지 않는 문제가 없나요?

아무리 테스트해두 넘어 가지 않네요.

확인 한번 부탁 드립니다.

**Comment by ikkang** [comment]
연속된 주문을 접수한 다음 연속한 주문을 완료처리 해주시면 됩니다.
