### ISSUE TITLE
연속된 주문 문의드립니다.

### ISSUE THREAD

**Issue by linkbp** [woowabros/OrderRelaySampleCode#11]
연속된 주문을 접수한 다음 주문완료처리를 해두 다음으로 넘어 가질 않습니다.

![20190820_144114_091](https://user-images.githubusercontent.com/51739659/63320501-f109cb00-c358-11e9-86a2-4d1075c270cd.jpg)

**Comment by ikkang** [comment]
UpdateDeliveryStatus를 사용하고 계셨다면 현재 테스트프로그램에서 동작하지 않으니  SetDeliveryCompleted함수를 사용해보시기 바랍니다.
샘플프로그램을 사용하여 프로그램이 동작하는지도 같이 테스트해보시기 바랍니다.
