### ISSUE TITLE
연속된 주문 처리 문의 입니다.

### ISSUE THREAD

**Issue by linkbp** [woowabros/OrderRelaySampleCode#12]
현재 SetDeliveryCompleted 함수를 사용하고 있습니다.

Test 시작을 눌러 두건을 받아 완료 처리 해두 안됩니다.
혹시 테스트는 해보셨나요?

확인 부탁 드립니다.

**Comment by ikkang** [comment]
방금 샘플코드를 수정해서 테스트 해봤고 DiagnosysDelivery.exe에 문제가 없는것을 확인했습니다.
두가지 상황이 의심됩니다.
첫번째 중복된 주문처리에 대한 처리코드는 샘플코드에 없습니다. 중복된 주문처리에 대한 대응코드는 직접 작성해야 합니다.
프로그램은 테스트 샘플코드 sampleData.json를 사용합니다. 이 파일의 샘플이 적기때문에 초기에 테스트한 중복된 주문번호가 다시 사용될 수 있습니다. 이미 완료된 주문번호는 중복주문 확인 로직에서 제거하시면 프로그램 테스트가 용이할 것 같습니다.

설명에도 써있듯 샘플코드로 모든 테스트를 통과할 수 없습니다. 샘플코드는 말 그대로 함수사용을 안내하기 위한 샘플입니다.
