### ISSUE TITLE
문의사항이 있습니다.

### ISSUE THREAD

**Issue by Jungjinchul** [woowabros/OrderRelaySampleCode#13]
배달대행 서비스를 제공하는 개발업체의 개발자 입니다.

현제 서류 심사를 통과를 못하여 개발 진행은 못하구 있으나, 
C++Builder 로 DiagnosysDelivery.exe 연동을 위한 테스트 프로그램을 완성해 놓은 상태 입니다.
물런 테스트도 통과 했구요.

궁금한 사항은
현제 상점들 중에 롯데리아 같은 프렌차이즈 업체에서 쓰고 있는, 배민주문접수 프로그램에서도
DLL 연동이 되는지요?

일반 상점용과  프렌차이즈용 배민 주문접수 프로그램이 조금 다른듯 보였습니다.
현제 DLL 연동이 되는지, 안되면 언제 되는지도 궁금 합니다.

보시면 꼭 답변 부탁 드립니다.

**Comment by ikkang** [comment]
답변이 늦어져 죄송합니다.
현재 우아한형제들에서 배포하고 있는 PC프로그램은 '배달의민족 주문접수_롯데리아'를 제외하고는 한가지 버전으로 모두 동일합니다. 롯데리아 버전은 다른 방식으로 배달대행을 연동하고 있으며 그런 이유로 dll연동은 진행하지 않을 것 입니다.
그 외의 프랜차이즈 에서 사용하는 프로그램은 우아한형제들에서 배포하는 프로그램이 아니며 그런 이유로 dll연동이 되지 않을 것 입니다.
