### ISSUE TITLE
연속된 주문 처리 관련 문의 입니다

### ISSUE THREAD

**Issue by hmn0708** [woowabros/OrderRelaySampleCode#14]
연속된 주문 처리 문의에서 테스트 시작을 클릭해서

생성된 2개의 주문을 완료 처리해도 

아래에  모든 주문을 완료처리했습니다로

진행되지 않는데 

c# 샘플코드 이용해 테스트 중이며

폼에 SetDeliveryCompleted 함수로 연동되어 있는 상태입니다.

중복된 주문처리에 대한 처리코드는 추가해 두었는데

연속된 주문도 다른 처리 코드를 추가해주거나 해야되는건지요?

**Comment by ikkang** [comment]
샘플코드로는 모든 테스트를 통과할 수 없습니다.
테스트코드는 함수의 사용설명을 위한 샘플이라고 이해해주시고 테스트 프로그램의 요구사항을 만족하는 프로그램을 제작해주시기 바랍니다.
테스트 샘플이 적기때문에 바로 직전 테스트 결과와 겹치는 문제가 발생할 수 있습니다.(중복된 주문번호 등)
테스트를 진행할 때마다 초기화를 해야할 항목은 초기화 해주시거나 샘플데이터를 추가로 집어넣어 테스트를 진행하시기 바랍니다.
