### ISSUE TITLE
안녕하세요 재접속 확인 테스트에 관한 질문입니다.

### ISSUE THREAD

**Issue by KimDohoon-commits** [woowabros/OrderRelaySampleCode#15]
안녕하세요 항상 고생이 많으십니다.
다름이 아니오라 Diagnosys Program에서 재접속 확인테스트 시
배달의민족 프로그램이 갑작스레 종료되거나 다시 시작 될 경우 라고 되어 있는데
이런 경우라면 제가 생각하기에 배민프로그램을 사용하는 가맹점의 SignKey와 ID가 있어야 테스트가 가능한 부분이 아닌가 싶어 조심스레 여쭤봅니다.

**Comment by Kim-Suhyeon** [comment]
저도 궁금한 부분입니다. 빠른 답변 부탁드립니다.

**Comment by ikkang** [comment]
Diagnosys Program에서 비슷한 상황을 재현하여 테스트 할 수 있도록 하는 것 입니다.
테스트케이스를 통과하셨다면 기능이 동작하는 것으로 보고 연동요청 하시면 됩니다.
실제 운영하는 계정으로 기능테스트는 연동요청 후 배달의민족 개발자와 메신저나 전화로 통화하면서 최종 테스트를 진행하게 됩니다.
개략적인 일정은 위키를 참조하세요.
https://github.com/woowabros/OrderRelaySampleCode/wiki

**Comment by KimDohoon-commits** [comment]
그렇다면 재접속 확인 테스트에서 타이머가 시작된다는 것은 가맹점에서 사용하는 배민프로그램의 갑작스런 접속끊김 이후에 재접속이 시작될때부터의 시간이라고 가정하고 개발을 하면 되는걸까요??
