### ISSUE TITLE
재접속 확인에 대한 추가 질문입니다.

### ISSUE THREAD

**Issue by KimDohoon-commits** [woowabros/OrderRelaySampleCode#16]
그렇다면 재접속 확인 테스트에서 타이머가 시작된다는 것은 가맹점에서 사용하는 배민프로그램의 갑작스런 접속끊김 이후에 재접속이 시작될때부터의 시간이라고 가정하고 개발을 하면 되는걸까요??

**Comment by ikkang** [comment]
재접속 확인 페이지에 접속하면 랜덤한 시간 내에 테스트 프로그램이 접속 가능한 상태가 됩니다.
접속 가능 상태가 된 이후로 5초 이내에 다시 접속을 시도하는지를 테스트 합니다.
즉 접속이 유지되어야 하는 상태에 접속이 끊겨 있다면 재접속을 시도하는 코드를 5초 이내의 간격으로 시도해주시면 됩니다.
