### ISSUE TITLE
재접속 확인 페이지에서 정상적인 종료와 비정상 적인 종료의 차이를 알 수 있는 함수구문이 어딘지 알 수 있을까요??

### ISSUE THREAD

**Issue by Kim-Suhyeon** [woowabros/OrderRelaySampleCode#18]
재접속 확인 페이지에서 정상적인 종료와 비정상 적인 종료의 차이를 알 수 있는 함수구문이 어딘지 알 수 있을까요??

**Comment by Kim-Suhyeon** [comment]
프로그램에서 비정상적 종료 카운터 시 비정상적 종료에 대한 부분이라고 알 수 있을 만한 함수실행부분이 전혀 없어 여쭤봅니다.

**Comment by ikkang** [comment]
정상적으로 종료를 시도하게 되면 FinalizeService 함수를 호출하고 이 호출의 결과로 모든 Callback 함수들의 등록이 해제됩니다. 즉 정상적으로 종료를 시도할 때는 RegisterDisconnectFunction에서 등록한 이벤트가 발생하지 않지만 의도하지 않게 접속이 종료된 경우 이 Callback 함수가 발생합니다.
