### ISSUE TITLE
DLL 주문연동 API 개발

### ISSUE THREAD

**Issue by linkbp** [woowabros/OrderRelaySampleCode#2]
제휴사 입니다.

연동테스트에는 문제없이 잘 진행 되고 있습니다.
누락된 데이터가 있어 문의 드립니다.

배달팁, 주문일시, 요청사항 
혹시 앞으로 추가 될수 있는 데이터인가요?

그리고 전체 메뉴를 다 줄수는 없는건가요?

답변 부탁 드립니다.
감사합니다.

**Comment by ikkang** [comment]
배달의민족에서 제공되는 배달팁정보는 설정할 수 있는 여러가지 방법이 존재하나 실제로 배달대행사에 지불해야 할 금액과는 다를 수 있습니다. 실제로 배달팁은 설정에 의해 사용할수도 사용하지 않을 수도 있어 참고할 수 있는 정보가 아닙니다.
주문일시는 실제로 전달되지는 않으나 주문을 접수하는 시점에 주문정보가 전송되고 주문은 발생 후 3분 이내에 접수하지 않으면 자동으로 취소되기 때문에 이벤트를 받은 시점에서 최대 3분 이내라고 간주하시면 됩니다. 예약주문의 경우 조리를 시작해야하는 시점에 전달됩니다.
요청사항은 현재 업주와 라이더 요청사항을 분리하는 것을 검토중이며 이 작업이 완료되면 V2에 요청사항을 반영하도록 하겠습니다.

 전체메뉴를 전송하는 것은 여러 개발툴을 지원해야하는 Dll의 특성상 Generic형태의 데이터가 아닌 2차원 배열 형태의 원시데이터가 추가되어야 하는데 이 때 구현의 난이도가 올라가는 단점이 있고 또한 전체 메뉴정보가 배달에 반드시 필요한 정보가 아니라고 판단했기 때문에 제공하지 않는 것 입니다.

**Comment by linkbp** [comment]
한가지더 궁금한 사항이 있습니다.
amount 는 주문 금액 + 배달팁인가요?

주문금액 만 표기 된건가요?

**Comment by ikkang** [comment]
주문금액과 배달팁이 모두 포함된 최종 결재해야할 금액입니다.

**Comment by linkbp** [comment]
자꾸 궁금증이 나오네요.^^
RegisterNewDeliveryFunction 은 주문이 접수 되었을때 호출 되는함수로 문서에두 나와 있지만.
새로운 주문이 발행 했을때 호출 되는 함수는 아니죠?

제휴사 정책은 배달대행사 완료후 3시가 이후 마킹 처리입니다.
그런데 콜은 접수후 자체 배달도 갈수 있고 대행사 호출로 배달은 처리 할수 있습니다.

OS_COMPLETED   2  주문이 완료됨
혹시 OS_COMPLETED 기준은 어떻게 되나요?
- 가맹점에서 완료처리
- 배민 시스템에서 주문접수후 일정시간이 지나면 완료 처리 

완료 처리를 왜 보냐면 자체 배달인 경우 가맹점주가 완료 처리를 해도 되지만
배민의 완료 처리 상태를 보고 자동 완료 처리후 마킹처리 관련해서 이슈가 있어 문의 드립니다.
감사합니다.

**Comment by ikkang** [comment]
RegisterNewDeliveryFunction을 사용해서 등록한 Callback함수가 호출되는 시점은 두가지 입니다.
첫번째는 발생한 주문을 업주님이 접수했을 때(취소한 주문은 함수가 호출되지 않습니다.)
두번째는 예약주문의 조리를 시작해야할 시점이 되었을 때(조리시작 알림이 울립니다.)
두가지 모두 업주님이 조리를 시작하는 시점이라고 이해하시면 됩니다.

TOnStatusChangedProc에서 전달되는 상태정보중 처리해야 할 항목은 OS_COMPLETED 인데
이는 두가지 경우에서 발생합니다.
첫번째는 업주님이 주문상세에서 배달완료를 클릭할 경우이고
두번째는 접수한 주문이 세시간이 경과했을 때 입니다.
SetDeliveryCompleted 함수를 호출할때도 배달완료를 클릭하는 경우와 마찬가지로 배달완료 처리가 되고 동일하게 TOnStatusChangedProc Callback이 호출됩니다.
해당 이벤트는 개인정보 보호와 관련된 이슈로 전송하는 것 입니다. 개인정보를 업소에서 소유할 수 있는 기간은 주문이 발생한 시점부터 주문이 완료될 때 까지 입니다. 그 이후에 개인정보를 수집하는 것은 불법이며 이로 인해 PC접수는 배달완료 처리되는 순간 모든 개인정보를 삭제합니다.

즉 문의하신 의도와 일치하는 순간에 Callback 이벤트가 발생합니다. 이벤트를 받았을 때 마스킹처리하시면 됩니다.

**Comment by linkbp** [comment]
연속된 주문처리
저희 쪽에서 완료를 던졌지만... 체크 박스가 그냥 가만히 있습니다.
뭐가 문제일까요?
![연속된 주문처리에러](https://user-images.githubusercontent.com/51739659/59652086-37ab3f80-91c7-11e9-90c2-d2e3bc8e72e7.png)

**Comment by lpoint1** [comment]
안녕하세요? 
제휴하고 싶은데 담당자 알 수 있을까요?

**Comment by ddaun** [comment]
lpoin1님 안녕하세요.

https://github.com/woowabros/OrderRelaySampleCode/wiki

이쪽 참고 부탁드립니다.
