### ISSUE TITLE
TOnNewDeliveryFunc Function 업그레이드 

### ISSUE THREAD

**Issue by soonge4** [woowabros/OrderRelaySampleCode#20]
TOnNewDeliveryFunc 콜백 함수에서 
주문 메뉴 상세 정보 ( 메뉴 리스트/메뉴별 금액/ 메뉴별 수량)는 연동이 안되고 있는데요.
해당 정보도 받을 수 있게끔 업그레이드가 가능한지 문의드립니다.

**Comment by ikkang** [comment]
해당함수를 단기간에 수정하거나 내용을 추가할 계획은 아직 업습니다.
