### ISSUE TITLE
안녕하세요. 궁금한 사항이 있습니다.

### ISSUE THREAD

**Issue by 5HARK** [woowabros/OrderRelaySampleCode#21]
안녕하세요. 문자열 관련 메모리 해제와 관련된 질문입니다.

콜백 Function 들중 `TOnNewDeliveryFunc` 함수로 예를 들어보자면 
함수 시그니처가 
```CPP
boolean TOnNewDeliveryFunc(WCHAR[] AOrderNo, WCHAR[] ARoadNameAddress, WCHAR[] AAddress, WCHAR[] AAddressDetail, WCHAR[] APhoneNo, WCHAR[] ALatitude, WCHAR[] ALongitude, WCHAR[] ATitle, int AQuantity, int AAmount, int APaymentType, WCHAR[] AMemo);
```
이런 식인데요.

보시면 WCHAR[] 형태로 스트링들이 넘어오는데 이 문자열 배열들의 메모리 해제는 연동업체측에서 해야되는 부분인가요? 아니면 해제해주는 동작이 DLL 안에 내장되어 있는건가요?

아니면 배민측에서 호출해주실때 상위함수에 Stack 영역의 있는 단순 고정값 문자열 배열이라 해제할 필요가 없는건가요?

**Comment by jhjang-woowahan** [comment]
안녕하세요 5HARK님,

파라미터로 넘어간 값들의 메모리 해제는 필요 없습니다.넘기는 값은 Heap에서 선언되고, 호출 이후 Heap에서 사라지게 됩니다.
유지가 필요하면 변수로 받아 사용하시면 될것 같습니다.

**Comment by 5HARK** [comment]
안녕하세요. 답변 감사합니다.

그러면 연동업체 측의 사전에 등록된 콜백함수의 실행이 끝나고 리턴된 이후 배민측에서 해당 변수에 대한 메모리 부분을 해제/정리해주신다고 이해하면 될까요?

**Comment by jhjang-woowahan** [comment]
넵. 해당 메모리는 DLL 에서 회수하게 됩니다.
