### ISSUE TITLE
중복된 주문 처리 문의드립니다.

### ISSUE THREAD

**Issue by Esei1541** [woowabros/OrderRelaySampleCode#26]
테스트 프로그램으로 개발을 진행하고 있습니다.

중복된 주문 처리 부분에서 설명된 조건을 만족한 것 같은데 통과가 되지 않아 문의드립니다.

TOnNewDeliveryFunc를 통해 들어온 주문 정보를 저희측 서버로 보내고, 서버에서는 AOrderId가 중복되면 특정 에러 코드를 리턴합니다. (중복되지 않았을 시에는 서버에 주문 정보를 정상적으로 등록)
클라이언트에서는 해당 코드를 받았을 때 TOnNewDeliveryFunc의 return값으로 false를 보내게 됩니다.

이후 첫번째로 들어온 주문을 완료 처리하면 통과가 될 거라고 생각했는데, 정작 첫 번째 조건인 '주문이 중복되었음을 확인했습니다.'가 완료되지 않습니다.

중복된 주문이 들어왔을 때 TOnNewDeliveryFunc에서 false를 리턴하는 것 외에 수행해야 할 조건이 더 있는 건가요?

**Comment by ddaun** [comment]
안녕하세요!

해당 테스트는 false를 리턴해주시는 것 외에 수행 할 작업은 따로 없습니다.

false를 정상적으로 리턴하는지 확인 부탁드립니다.

감사합니다!
