### ISSUE TITLE
인증키 문의

### ISSUE THREAD

**Issue by yahr** [woowabros/OrderRelaySampleCode#27]
기존에 설치되어 있는 PC용 주문 프로그램 사용자의 인증키는 어떻게 알 수 있을까요 ?

**Comment by ddaun** [comment]
안녕하세요! 

질문하신 내용이 연동서비스 중인 대행사의 키 관련 문의시면

아래 메일 주소로 문의 부탁드립니다.

bmpos.biz@woowahan.com 

감사합니다.
