### ISSUE TITLE
추가 배달대행 연동 공지는 어디서 확인할 수 있나요?

### ISSUE THREAD

**Issue by leetaeheon123** [woowabros/OrderRelaySampleCode#29]
4분기 배달대행 연동 신청 공지는 어디서 확인할 수 있나요?

**Comment by ddaun** [comment]
안녕하세요. 
해당 내용은 본 저장소 wiki페이지 에서 확인하실 수 있습니다.
https://github.com/woowabros/OrderRelaySampleCode/wiki

추가 문의는 bmpos.biz@woowahan.com 이 쪽으로 부탁드립니다.

감사합니다.
