### ISSUE TITLE
DiagnosysDelivery.exe 작동 되지 않음

### ISSUE THREAD

**Issue by step4u** [woowabros/OrderRelaySampleCode#30]
안녕하세요.

dll 을 사용해서 프로그램을 연동하기위해 여기서 제공되는 DiagnosysDelivery.exe 프로그램으로

 "시작하기"버튼 눌러서 order 테스트를 진행하고 있는데 "서비스 접속을 확인합니다." 라고 뜨고 아무런 반응이 없습니다.

현재 dll을 사용할 수 있는지 확인 부탁드립니다.

dll 파일은 DiagnosysDelivery.exe 와 같은 폴더에 카피해넣었습니다.

**OS: Windows 11 Home**

![DiagnosysProgram01](https://user-images.githubusercontent.com/1725165/207809085-6e4aa75c-b240-442b-b892-817057e4ec54.png)

**Comment by ddaun** [comment]
안녕하세요! 

문의주신 내용을 보니 잘못된 방법으로 테스트를 진행하고 계신 것 같습니다.

`Service 초기화`는 추후 정식 계약 시 발급되는 키를 통한 연동 가능 여부와 주문을 처리할 수 준비상태를 테스트하는 단계입니다.

테스트 방법은 개발 중이신 프로그램에서 제공된 DLL을 Load하신 후 

첨부주신 이미지 기준 `인증키 :`항목의 값을 복사하여  

InitializeService함수의 parameter로 전달하여 호출하시면 됩니다.

정상적으로 성공된 경우 `서비스 접속을 확인합니다` **체크박스가 자동으로 체크**되며,

이후 `다음으로` 버튼이 활성화되어 다음 테스트 단계를 진행하실 수 있습니다.

제공중인 샘플 프로그램 코드와
https://github.com/woowabros/OrderRelaySampleCode/tree/master/C%23
https://github.com/woowabros/OrderRelaySampleCode/tree/master/Delphi
https://github.com/woowabros/OrderRelaySampleCode/tree/master/VisualBasic

[API문서](https://github.com/woowabros/OrderRelaySampleCode/blob/master/Bin/%EC%A3%BC%EB%AC%B8%EC%A0%95%EB%B3%B4%20%EC%97%B0%EB%8F%99%20API.pdf)를 참고하시면 어렵지 않게 진행하실 수 있을 것 같습니다.

감사합니다.
