### ISSUE TITLE
발생한 주문 완료처리 과정 문의

### ISSUE THREAD

**Issue by compcwGit** [woowabros/OrderRelaySampleCode#34]
안녕하세요.
현재 소스에 포함된 델파이 예제소스로 테스트 진행 중, 배달완료 처리가 되지않아 문의드립니다.

따로 수정한 내용은 없고 라이더 상태변경 showmodal 값 넘겨 받고나서
UpdateDeliveryStatus 함수를 이용해서 완료처리 세팅을 하는데
리턴값은 true 로 나오는데 테스트프로그램(Diagnosys Program) 에서는 '발생한 주문이 완료처리 되었습니다.' 
이 부분이 체크가 되지않아 다음 단계로 넘어가지 않습니다.

이 내용 확인부탁드리겠습니다.

감사합니다.

**Comment by ikkang** [comment]
델파이 샘플코드를 확인해봤는데 정상 동작하는 것 같습니다. 
혹시 샘플코드 변경한 부분이 있다면 원복 후 다시 시도해보시기 바랍니다.
디버깅 모드로 사용하고 있다면 Release 모드로 빌드 후 실행파일을 단독 실행했을 때에도 동일한 문제가 발생하는지 확인해주세요.

**Comment by compcwGit** [comment]
현재 델파이 7에서 테스트 진행중에 있습니다.
말씀해주신대로 Release 모드로 빌드 후 진행했을 때 동일한 증상이 확인되었습니다..
소스에서 수정한 내용은 UpdateDeliveryStatus 의 Return 값을 확인한 내용입니다.

      if UpdateDeliveryStatus(PWideChar(ItemData.OrderNo), rgDeliveryStatus.ItemIndex, PWideChar(edRiderCode.Text), PWideChar(edRiderName.Text), seETA.Value) then
        memo1.Lines.Add('UpdateDeliveryStatus 전달완료 ' + IntToStr(rgDeliveryStatus.ItemIndex))
      else
        memo1.Lines.Add('UpdateDeliveryStatus 전달실패');

이 결과 라이더 상태변경 시 memo1 에는 'UpdateDeliveryStatus 전달완료 2' 이렇게 표시되는데 Diagnosys Program 에서는 변화가 없습니다.
(하단 이미지 파일 첨부합니다.)

![test](https://github.com/user-attachments/assets/2201a875-28e0-4e90-be3a-e2c1b356f650)

혹시 추가로 확인해야 할 사항이 있는지 확인 부탁드리겠습니다.

**Comment by ikkang** [comment]
실제로 코드를 변경해서도 시도해봤으나 정상적으로 동작하고 있습니다.
실제로 변경한 코드가 그것뿐이고 정상적으로 완료처리를 했다면 더 이상 추가로 확인해볼 수 있는 내용은 없습니다.
<img width="1050" alt="image" src="https://github.com/user-attachments/assets/5715bbd0-6c82-474b-9270-1db536aaa26d">

**Comment by compcwGit** [comment]
안녕하세요.
해당 건은 OrderNo 가 깨져서 전송되는 증상으로 확인되어 다음과 같이 변경했습니다.
델파이 버전에 따른 인코딩 문제로 의심이 되어

UpdateDeliveryStatus(PWideChar(widestring(ItemData.OrderNo)), rgDeliveryStatus.ItemIndex, PWideChar(widestring(edRiderCode.Text)), PWideChar(widestring(edRiderName.Text)), seETA.Value)

이렇게 변경하니 정상적으로 처리되는 내용이 확인되었습니다.

단순히 PWideChar 로만 했을 때 텍스트가 깨져서 처리되는 내용이 있어 widestring으로 변환을 한뒤 처리를 하니 정상적으로 되는내용이 확인되었습니다.

같이 고민해주셔서 감사합니다.
