### ISSUE TITLE
RegisterNewDeliveryFunction return value

### ISSUE THREAD

**Issue by palangue** [woowabros/OrderRelaySampleCode#4]
RegisterNewDeliveryFunction 에서 배달 등록 여부에 대하여 true, false 를 리턴해 달라고 명시되어 있는데,

false 를 리턴 했을 때와 true를 리턴 했을 때 어떤 부분이 달라지는지요? 
주소나 가맹점 업주의 상황에 따라 바로 배달 등록이 지연 되어야 할 상황이 발생할 수 있어 false 를 리턴하는 상황이 발생합니다.

**Comment by ikkang** [comment]
RegisterNewDeliveryFunction에서 등록된 Callback함수의 리턴값은 주문번호가 같은 중복된 주문이 접수되었거나 파라메터에 처리할 수 없는 데이터가 있을 때 False를 리턴하시면 됩니다. 
배달등록의 지연과 같은 상황에서 리턴값으로 처리하는 것은 PC접수상에서 별다른 차이가 없으며 만일 그때 배달대행 등록이 불가하면 추후에 
주문상세에서 다시 배달대행을 요청할 수 있습니다.

<img width="423" alt="resend" src="https://user-images.githubusercontent.com/17286571/60074961-28943680-975f-11e9-869d-ed87751da8de.png">
