### ISSUE TITLE
인증키 적용은 어떤걸 해야 하나요?

### ISSUE THREAD

**Issue by kjaein77** [woowabros/OrderRelaySampleCode#5]
테스트유닛에 있는 테스트 인증키는 프로그램 실행시마다 변경이 되는데요.
검수버전의 테스트 인증키는 어떤걸 사용해야 하는지요?
별도로 전달받은 검수용 인증키는 없습니다.

**Comment by ikkang** [comment]
테스트용 인증키는 임의로 정한 키값을 테스트 요청을 할 때 저희측에 알려주시면 됩니다.
참고로 테스트인증키 입력창은 수정이 가능합니다. '시작하기' 버튼을 누르기 전에 인증키를 사용하고자 하는 키로 변경한 다음 테스트를 진행하시면 프로그램을 수정하지 않고 테스트가 가능합니다.
![image](https://user-images.githubusercontent.com/17286571/60245275-3ed4fa80-98f7-11e9-9b09-113f4870da32.png)
