### ISSUE TITLE
c# Release build crashing

### ISSUE THREAD

**Issue by palangue** [woowabros/OrderRelaySampleCode#6]
c# 에서 연동 dll 을 debug로 빌드 시 연동이 잘 되는데요.
Release 로 빌드 시에는 라이브러리 호출에 실패하고 있습니다.

배포 시에는 따로 DLL 이 제공 되는지요?

**Comment by ikkang** [comment]
Release Option에서 32비트 기본사용 옵션이 켜져서 발생한 문제였습니다.
설정에서 아래와 같이 기본사용 옵션을 꺼서 사용하면 됩니다.
![image](https://user-images.githubusercontent.com/17286571/60409177-7694b880-9bfd-11e9-9eb3-f82f5879a69e.png)
또한 반드시 64bit로 실행프로그램을 실행할 필요가 없다면 dll 로드부분을 무조건 32bit dll만 로드하도록 수정하여 사용해도 됩니다.

DLL은 현재 Git에 올라와있는 바이너리가 정식버전입니다.

**Comment by ikkang** [comment]
commit e3f510500c3554d21e6a9e407d7f395cffbcd376 에서 주정되었습니다.
