### ISSUE TITLE
API 문의

### ISSUE THREAD

**Issue by kjaein77** [woowabros/OrderRelaySampleCode#9]
제휴사 입니다. 

이번에 추가된 API 문서 중 UpdateDelivertyStatus  하단에
빨간색으로 해당 함수는 특정일 배포 버전에서는 기능적으로 동작하지 않을수 있으며 배포가 완료되면 이 공지는 문서에서 삭제 됩니다라고 되어 있습니다. 

삭제 된다는 것이 어떤 의미인지요?

UpdateDelivertyStatus 에서 처리를 하니
SetDeliveryCompleted  해당 함수가 삭제된다는 것인가요? ^^

**Comment by ikkang** [comment]
UpdateDelivertyStatus는 배달의 민족 서비스와 연동하여 배달대행 정보를 공유하고자 하는것이 목적이나 서버작업이 아직 끝나지 않아 정식 서비스가 이루어지지 않고 있습니다.
해당 작업이 완료되어 배달대행 정보를 소비자가 확인할 수 있는 기능이 완성되면 경고문구를 삭제할 예정입니다.(기능이 삭제되는 것이 아닙니다.)

UpdateDeliveryStatus와 SetDeliveryCompleted는 모두 유지되나 UpdateDeliveryStatus를 사용해도 향후 SetDeliveryCompleted를 사용한 것과 같이 완료처리 된다는 의미입니다.
UpdateDeliveryStatus("OrderNo", 2, ...)는 SetDeliveryCompleted("OrderNo")와 같은 결과를 가지게 됩니다.
